BIG_LARGE_CIRCLE = 261
LARGE_CIRCLE = 215
BIG_MEDIUM_CIRCLE = 160
MEDIUM_CIRCLE = 106
SMALL_CIRCLE = 53

WheelButtons = {
	[1] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot9/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/9',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_9',
		angle = 90,
		slice = 2,
		totalSlice = 4,
		radius = BIG_LARGE_CIRCLE,
	},
	[2] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot8/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/8',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_8',
		angle = 45,
		slice = 5,
		totalSlice = 8,
		radius = LARGE_CIRCLE,
	},
	[3] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot6/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/6',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_6',
		angle = 30,
		slice = 8,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[4] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot4/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/6',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_4',
		angle = 30,
		slice = 9,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[5] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot8/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/8',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_8',
		angle = 45,
		slice = 6,
		totalSlice = 8,
		radius = LARGE_CIRCLE,
	},
	[6] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot9/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/9',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_9',
		angle = 90,
		slice = 3,
		totalSlice = 4,
		radius = BIG_LARGE_CIRCLE,
	},
	[7] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot7/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/7',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_7',
		angle = 45,
		slice = 4,
		totalSlice = 8,
		radius = LARGE_CIRCLE,
	},
	[8] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot5/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/5',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_5',
		angle = 30,
		slice = 7,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[9] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot3/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/3',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_3',
		angle = 45,
		slice = 5,
		totalSlice = 8,
		radius = MEDIUM_CIRCLE,
	},
	[10] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot3/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/3',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_3',
		angle = 45,
		slice = 6,
		totalSlice = 8,
		radius = MEDIUM_CIRCLE,
	},
	[11] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot5/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/5',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_5',
		angle = 30,
		slice = 10,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[12] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot7/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/7',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_7',
		angle = 45,
		slice = 7,
		totalSlice = 8,
		radius = LARGE_CIRCLE,
	},
	[13] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot4/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/4',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_4',
		angle = 30,
		slice = 6,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[14] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot2/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/2',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_2',
		angle = 45,
		slice = 4,
		totalSlice = 8,
		radius = MEDIUM_CIRCLE,
	},
	[15] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_left/slot1/',
		borderImageBase = '/game_wheel/images/wheel-border/top_left/1',
		focusImageBase = '/game_wheel/images/wheel-colors/top_left/TopLeft_1',
		angle = 90,
		slice = 2,
		totalSlice = 4,
		radius = SMALL_CIRCLE,
	},
	[16] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot1/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/1',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_1',
		angle = 90,
		slice = 3,
		totalSlice = 4,
		radius = SMALL_CIRCLE,
	},
	[17] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot2/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/2',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_2',
		angle = 45,
		slice = 7,
		totalSlice = 8,
		radius = MEDIUM_CIRCLE,
	},
	[18] = {
		colorImageBase = '/game_wheel/images/wheel-colors/top_right/slot6/',
		borderImageBase = '/game_wheel/images/wheel-border/top_right/4',
		focusImageBase = '/game_wheel/images/wheel-colors/top_right/TopRight_6',
		angle = 30,
		slice = 11,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[19] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot4/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/4',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_4',
		angle = 30,
		slice = 5,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[20] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot2/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/2',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_2',
		angle = 45,
		slice = 3,
		totalSlice = 8,
		radius = MEDIUM_CIRCLE,
	},
	[21] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot1/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/1',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_1',
		angle = 90,
		slice = 1,
		totalSlice = 4,
		radius = SMALL_CIRCLE,
	},
	[22] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot1/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/1',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_1',
		angle = 90,
		slice = 0,
		totalSlice = 4,
		radius = SMALL_CIRCLE,
	},
	[23] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot3/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/2',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_3',
		angle = 45,
		slice = 0,
		totalSlice = 8,
		radius = MEDIUM_CIRCLE,
	},
	[24] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot6/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/4',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_6',
		angle = 30,
		slice = 0,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[25] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot7/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/7',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_7',
		angle = 45,
		slice = 3,
		totalSlice = 8,
		radius = LARGE_CIRCLE,
	},
	[26] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot5/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/5',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_5',
		angle = 30,
		slice = 4,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[27] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot3/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/3',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_3',
		angle = 45,
		slice = 2,
		totalSlice = 8,
		radius = MEDIUM_CIRCLE,
	},
	[28] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot2/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/3',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_2',
		angle = 45,
		slice = 1,
		totalSlice = 8,
		radius = MEDIUM_CIRCLE,
	},
	[29] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot5/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/5',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_5',
		angle = 30,
		slice = 1,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[30] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot8/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/7',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_8',
		angle = 45,
		slice = 0,
		totalSlice = 8,
		radius = LARGE_CIRCLE,
	},
	[31] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot9/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/9',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_9',
		angle = 90,
		slice = 1,
		totalSlice = 4,
		radius = BIG_LARGE_CIRCLE,
	},
	[32] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot8/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/8',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_8',
		angle = 45,
		slice = 2,
		totalSlice = 8,
		radius = LARGE_CIRCLE,
	},
	[33] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_left/slot6/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_left/6',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_left/BottonLeft_6',
		angle = 30,
		slice = 3,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[34] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot4/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/6',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_4',
		angle = 30,
		slice = 2,
		totalSlice = 12,
		radius = BIG_MEDIUM_CIRCLE,
	},
	[35] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot7/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/8',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_7',
		angle = 45,
		slice = 1,
		totalSlice = 8,
		radius = LARGE_CIRCLE,
	},
	[36] = {
		colorImageBase = '/game_wheel/images/wheel-colors/bottom_right/slot9/',
		borderImageBase = '/game_wheel/images/wheel-border/bottom_right/9',
		focusImageBase = '/game_wheel/images/wheel-colors/bottom_right/BottonRight_9',
		angle = 90,
		slice = 0,
		totalSlice = 4,
		radius = BIG_LARGE_CIRCLE,
	},
}

WheelSettings = {
	topLeft = {1, 2, 7, 3, 8, 13, 9, 14, 15},
	topRight = {6, 5, 12, 4, 11, 18, 10, 17, 16},
	bottomLeft = {31, 25, 32, 33, 26, 19, 27, 20, 21},
	bottomRight = {36, 35, 30, 34, 29, 24, 28, 23, 22},
}

--215
--160
--106