#!/usr/bin/env python3
# Usage guide:
# 1) Generate with default paths:
#    python3 tools/generate_cyclopedia_houses_lua.py
#
# 2) Generate with custom input/output:
#    python3 tools/generate_cyclopedia_houses_lua.py \
#      --xml /home/jp/Documentos/github/canary/data-otservbr-global/world/otservbr-house.xml \
#      --out modules/game_cyclopedia/houses_data.lua
#
# 3) After updating Canary houses XML, run again to refresh the Lua table.
"""Generate Lua house metadata table for Cyclopedia from Canary house XML."""

from __future__ import annotations

import argparse
import datetime as dt
import pathlib
import sys
import xml.etree.ElementTree as ET


def parse_bool(value: str | None) -> bool:
    if not value:
        return False
    return value.strip().lower() in {"1", "true", "yes"}


def to_int(value: str | None, default: int = 0) -> int:
    if not value:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def lua_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def infer_shop(name: str) -> int:
    lower = name.lower()
    return 1 if "(shop)" in lower or " shop" in lower else 0


def generate(xml_path: pathlib.Path, output_path: pathlib.Path) -> tuple[int, int]:
    root = ET.parse(xml_path).getroot()
    if root.tag != "houses":
        raise ValueError(f"Unexpected root tag '{root.tag}', expected 'houses'")

    rows: list[dict[str, object]] = []
    for node in root.findall("house"):
        client_id = to_int(node.attrib.get("clientid"))
        if client_id <= 0:
            continue

        name = node.attrib.get("name", "").strip()
        rows.append(
            {
                "client_id": client_id,
                "house_id": to_int(node.attrib.get("houseid")),
                "name": name,
                "rent": to_int(node.attrib.get("rent")),
                "beds": to_int(node.attrib.get("beds")),
                "sqm": to_int(node.attrib.get("size")),
                "town_id": to_int(node.attrib.get("townid")),
                "entryx": to_int(node.attrib.get("entryx")),
                "entryy": to_int(node.attrib.get("entryy")),
                "entryz": to_int(node.attrib.get("entryz")),
                "gh": 1 if parse_bool(node.attrib.get("guildhall")) else 0,
                "shop": infer_shop(name),
            }
        )

    rows.sort(key=lambda r: int(r["client_id"]))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with output_path.open("w", encoding="utf-8") as fh:
        fh.write("-- Auto-generated by tools/generate_cyclopedia_houses_lua.py\n")
        fh.write(f"-- Source: {xml_path}\n")
        fh.write(f"-- Generated at: {now}\n\n")
        fh.write("HOUSE = HOUSE or {}\n\n")
        for row in rows:
            fh.write(
                "HOUSE[{client_id}] = {{id = {house_id}, name = \"{name}\", description = \"\", "
                "rent = {rent}, beds = {beds}, sqm = {sqm}, GH = {gh}, shop = {shop}, townId = {town_id}, "
                "entryx = {entryx}, entryy = {entryy}, entryz = {entryz}}}\n".format(
                    client_id=row["client_id"],
                    house_id=row["house_id"],
                    name=lua_quote(str(row["name"])),
                    rent=row["rent"],
                    beds=row["beds"],
                    sqm=row["sqm"],
                    gh=row["gh"],
                    shop=row["shop"],
                    town_id=row["town_id"],
                    entryx=row["entryx"],
                    entryy=row["entryy"],
                    entryz=row["entryz"],
                )
            )

    return len(rows), len({int(r["client_id"]) for r in rows})


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Cyclopedia houses metadata Lua file from Canary houses XML."
    )
    parser.add_argument(
        "--xml",
        default="/home/jp/Documentos/github/canary/data-otservbr-global/world/otservbr-house.xml",
        help="Path to canary houses XML file.",
    )
    parser.add_argument(
        "--out",
        default="modules/game_cyclopedia/houses_data.lua",
        help="Output Lua path.",
    )
    args = parser.parse_args()

    xml_path = pathlib.Path(args.xml).expanduser().resolve()
    out_path = pathlib.Path(args.out).resolve()

    if not xml_path.exists():
        print(f"[error] XML not found: {xml_path}", file=sys.stderr)
        return 1

    try:
        rows, unique_client_ids = generate(xml_path, out_path)
    except Exception as exc:  # noqa: BLE001
        print(f"[error] Failed to generate Lua: {exc}", file=sys.stderr)
        return 1

    print(f"[ok] Generated: {out_path}")
    print(f"[ok] Houses exported: {rows} (unique client IDs: {unique_client_ids})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
